algoritmo "26"
// Autora: Gabriela
// 05/12/2024
var
   N1,N2: inteiro
inicio
      Escreva ("Digite o primeiro número: ")
      Leia (N1)
      Escreva ("Digite o segundo número: ")
      Leia (N2)
      Se (N1>N2) entao
         Escreva ("O primeiro valor é o maior.")
      senao
           Se (N2>N1) entao
              Escreva ("O segundo valor é o maior.")
           senao
                Escreva ("Não existe valor maior, os dois são iguais.")
           FimSe
      FimSe
fimalgoritmo