algoritmo "8"
// Autora: Gabriela
// 05/12/2024
var
   m, Km, Hm, Dam, Dm, Cm, Mm: real
inicio
      Escreva ("Digite uma distância em metros: ")
      Leia (m)
      Km <- m/1000
      Hm <- m/100
      Dam <- m/10
      Dm <- m*10
      Cm <- m*100
      Mm <- m*1000
      Escreval ("A distância de ", m, "m corresponde a:")
      Escreval (Km, "Km")
      Escreval (Hm, "Hm")
      Escreval (Dam, "Dam")
      Escreval (Dm, "Dm")
      Escreval (Cm, "Cm")
      Escreval (Mm, "Mm")
fimalgoritmo